# Generated by Django 2.2.6 on 2019-11-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerias',
            options={'verbose_name': 'galeria', 'verbose_name_plural': 'galerias'},
        ),
    ]
