# Generated by Django 2.2.6 on 2019-11-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerias',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galerias.Category'),
        ),
    ]
