# Generated by Django 2.2.6 on 2019-11-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0004_galerias_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
