# Generated by Django 2.2.6 on 2019-10-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
