# Generated by Django 2.2.6 on 2019-11-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicios_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
