# Generated by Django 2.2.6 on 2019-11-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20191103_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
