# Generated by Django 2.2.6 on 2019-11-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicios_categoria'),
        ('servicios', '0003_auto_20191102_2353'),
    ]

    operations = [
    ]
