# Generated by Django 2.2.6 on 2019-12-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_merge_20191116_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
