# Generated by Django 2.1.7 on 2019-12-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservas_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={'permissions': (('gerente', 'Es gerente'), ('cliente', 'Es cliente'))},
        ),
    ]
